### ISSUE TITLE
document mycelium client OSX and Windows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#618] opened 2024-08-07 19:03 UTC
check with @maximevanhees 
the goal is to document creating a vm with mycelium and using that mycelium client to be enable to connect to that machine

**Comment by Mik-TF** [comment] 2024-08-08 21:35
Can you add some info? There seems to be many ways to proceed. Here's a proposition:

- Show the basic steps to install mycelium on a VM: basically a summary of https://manual.grid.tf/documentation/system_administrators/mycelium/mycelium_toc.html but adapted for VM

Is this sufficient? Do we want two guides: micro and full VMs?

**Comment by xmonader** [comment] 2024-08-08 21:38
There's a desktop application developed/in the process of being developed by @maximevanhees . That's what needs to be integrated in the manuals (not duplicating content for sure)

**Comment by Mik-TF** [comment] 2024-08-08 23:07
OK good! Then Maxime can communicate when its ready to be shared/added to the manual, and if there are repos in particular with any docs to work with.

**Comment by Mik-TF** [comment] 2024-08-09 18:43
# Notes

For now, Mycelium is sufficiently covered only for Linux: https://manual.grid.tf/documentation/system_administrators/mycelium/mycelium_toc.html

Once we have the client for OSX and Windows, we can update the Mycelium section (shared in the link above) with OSX and Windows.

**Comment by Mik-TF** [comment] 2024-08-12 19:16
@maximevanhees 

What is the status+ETA of the OSX + Windows client? Just to get a pulse of the situation and plan forward. Thanks!

**Comment by maximevanhees** [comment] 2024-08-13 08:53
@Mik-TF @xmonader

At this moment there is a branch (mycelium-ui) that uses Dioxus, a Rust GUI library, to create a "frontend" for Mycelium where user can lookup and search routes and view which peers they are connected to. At this moment the codebase is only tested on Linux. I'll test how it behaves on MacOS and Windows today, but normally this shouldn't be an issue as Dioxus says it is designed to be cross-platform by default. Note that this UI doesn't include the Mycelium binary itself, and thus users are still required to manually start Mycelium beforehand.

On another note: I've already created a Windows installer for Mycelium (using WiX) but it does not automatically start up as a background service yet. The goal here is to provide a more user-friendly experience for less technical users that want to run Mycelium. On Windows, we could package the binary and the GUI together (which would both get installed at once with the installer) providing a working out-of-the-box experience.

@despiegk also asked me to take a look at Flet.dev, a Python wrapper around Flutter (with some extra features) which aims to simplify the process of building a simple frontend for (exisiting) applications. I'm in the process of porting the Dioxus application to a Flet app, but I doubt how reliable it will be to deploy a Python codebase cross-platform (Linux, MacOS, Windows and mobile). At this moment there are still a couple of issues getting it to work properly.

**Comment by iwanbk** [comment] 2024-08-13 08:58
> also asked me to take a look at Flet.dev, a Python wrapper around Flutter (with some extra features) which aims to simplify the process of building a simple frontend for (exisiting) applications

@maximevanhees why we need to wrap Flutter with python?

**Comment by maximevanhees** [comment] 2024-08-13 09:08
@iwanbk I was just briefly mentioning what a Flet app is, nothing more 😊

**Comment by Mik-TF** [comment] 2024-11-04 20:32
@maximevanhees Hi! What is the status of this? Can we start to write the docs? Are there any docs started yet? Even if it's just some notes, it can help. Thanks.

**Comment by Mik-TF** [comment] 2024-11-11 13:03
As I understand, we can soon start documenting the mycelium GUI as 3.15 is released tomorrow. @maximevanhees lmk

**Comment by maximevanhees** [comment] 2024-11-11 15:36
@Mik-TF I'm not working on the GUI anymore, it has been handed over to @iwanbk. He will be able to give you an update.

**Comment by iwanbk** [comment] 2024-11-12 03:26
Hi @Mik-TF 
For Windows client, it is available on this release page https://github.com/threefoldtech/myceliumflut/releases
For osx: it is still `in review` on AppStore
![image](https://github.com/user-attachments/assets/2b4411b1-8610-40d4-a5e4-afc9275c1d4b)

I just released the iphone version to appstore few minutes ago, might need up to 24 hours to be publicly available 
![image](https://github.com/user-attachments/assets/d3a926ba-f4d0-44b5-8f68-3fc2d46abe4f)


I actually submitted the macos version before the iphone one, not sure why the macos version take longer time.

**Comment by iwanbk** [comment] 2024-11-12 03:27
FYI, the android one still on review.
Mostly about documents / paperwork :(

**Comment by Mik-TF** [comment] 2024-11-12 13:38
OK good. Thanks for the update. Really appreciated.

When it's all done, please update this issue so we can work on the docs and I can help as much as possible.

**Comment by iwanbk** [comment] 2024-12-03 07:31
Hi @Mik-TF 

The macos client is available at https://apps.apple.com/id/app/mycelium-network/id6504277565
It is on v0.8.0

There is some improvement on `TestFlight` for these issues https://github.com/threefoldtech/myceliumflut/issues/created_by/khaledyoussef24

I'll release the v0.9.0 after the fixes confirmed by @khaledyoussef24

**Comment by Mik-TF** [comment] 2024-12-05 13:55
Great! Thanks.

The iOS + Android guide is already published.

Will work on the macOS + Windows version then make a quick basic guide, then we can close this issue. Thanks for the links. That is what I was missing to complete it.

**Comment by Mik-TF** [comment] 2024-12-05 17:28
# Update

- Made a PR with the windows and macos version
- Add info on how to SSH with mycelium once it's installed

**Closed** 2024-12-09 15:07 UTC
